Попробовал потестировать ClientVersionService
Smartel1/StrikeComJava pull request #70
Opened 2020-05-05 21:12 UTC by MuradTcen

2020-05-06 17:34 UTC, Smartel1 requested changes

2020-05-06 17:34 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        when(repository.getByVersionAndClientId(any(String.class), any(String.class))).thenReturn(Optional.empty());
можно не использовать any(), ты ведь точно знаешь, какие аргументы будут переданы в этот метод

2020-05-06 17:34 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        assertThrows(ValidationException.class, () -> service.getNewVersions(getNewRequestDto));
можно проверить не только тип исключения, но и содержимое поля errors

2020-05-06 17:34 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        assertSame(VERSION, versions.getData().get(0).getVersion());
почему assertSame? здесь лучше подойдет assertThat(...).isEqualTo(...)

2020-05-06 17:34 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        assertSame(VERSION, versions.getData().get(0).getVersion());
И почему ты сравниваешь только одно поле в результате? Можно было сделать переменную expected, в которую ты запишешь всё то, что ожидаешь увидеть в результате работы метода. И потом сравнивать, чтo содержимое expected совпадает с actual

2020-05-06 17:34 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        assertNull(version.getOptionalFields().get(DESCRIPTION_RU));
тест надо было построить иначе:
1. создаешь переменную RequestDto
2. мок repository. getByVersionAndClientId у тебя правильный (но можно не использовать any())
3. var actual = <вызов подопытного метода с созданным в п.1 dto> (в твоём случае надо переименовать переменную version)
4. verify(reposutory.save()) с нужным аргументом (нам ведь надо убедиться, что репозиторий будет получать команду на сохранение)
5. assertThat(actual).isEqualTo(expected), где expected - ожидаемый на выходе объект, который будет создан специально для сравнения. Так не придётся проверять по одному полю.

2020-05-06 17:34 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        clientVersionDTO.setVersion(VERSION);
для создания этих объектов ты можешь просто создать в этом классе статические фабричные методы и вызывать по мере необходимости. Конечно же не надо создавать эти объекты для каждого теста, если они нужны не везде

2020-05-06 17:34 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        assertNull(version.getOptionalFields().get("description"));
этот тест можно объединить с предыдущим, ведь они тестируют одно и то же поведение, а меняются только входные данные и ожидаемый результат. Используй @ParametrizedTest

2020-05-06 17:34 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +                .thenReturn(java.util.Optional.of(new ClientVersion()));
java.util.Optional - используй импорт

2020-05-06 17:34 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        assertThrows(ValidationException.class, () -> service.create(requestDto));
можно добавить проверку на содержимое исключения

2020-05-06 17:34 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +    }
можно протестировать поведение, когда сущность существует, и мы её удаляем. То есть опять на помощь придёт метод verify()

2020-05-06 17:34 UTC, Smartel1 commented on src/main/java/ru/smartel/strike/service/client_version/ClientVersionService.java
> +        return clientVersions;
Этот метод можно упростить иначе:  
```
 public ListWrapperDTO<ClientVersionDTO> getNewVersions(ClientVersionGetNewRequestDTO dto) {
        clientVersionDTOValidator.validateListRequestDTO(dto);

        List<ClientVersionDTO> newVersions = Optional.ofNullable(dto.getCurrentVersion())
                // Если указана версия - находим более поздние версии клиентского приложения
                .map(v -> {
                    ClientVersion currentVersion = clientVersionRepository.getByVersionAndClientId(v, dto.getClientId())
                            .orElseThrow(() -> new ValidationException(
                                    Collections.singletonMap("error", Collections.singletonList(
                                            "Нет такой версии: " + dto.getClientId() + ":" + v))));

                    return clientVersionRepository.findAllByIdGreaterThanAndClientId(
                            currentVersion.getId(), dto.getClientId());
                })
                // Если версия не указана - находим все версии клиентского приложения
                .orElse(clientVersionRepository.findAllByClientId(dto.getClientId()))
                .stream()
                .map(cv -> ClientVersionDTO.of(cv, dto.getLocale()))
                .collect(Collectors.toList());

        return new ListWrapperDTO<>(newVersions, null);
    }

2020-05-08 09:07 UTC, Smartel1 requested changes

2020-05-08 09:07 UTC, Smartel1 commented on src/main/java/ru/smartel/strike/service/client_version/ClientVersionService.java
> +                // Если версия не указана - находим все версии клиентского приложения
везде по коду комментарии на английском, давай придерживаться этого

2020-05-08 09:07 UTC, Smartel1 commented on src/main/java/ru/smartel/strike/dto/request/client_version/ClientVersionCreateRequestDTO.java
> +        private Locale locale;
создавать билдер только для того, чтобы использовать его в тестах - не фонтан. здесь ты добавил больше 50 строк, и никакого проку от этого нет. В тестах можно было воспользоваться сеттерами

2020-05-08 09:07 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +                .build();
пока нет нужды использовать билдеры

2020-05-08 09:07 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        return new ClientVersionCreateRequestDTO.Builder()
надо использовать статический метод builder(), а не конструктор

2020-05-08 09:07 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        assertTrue(actual.contains(expected));
это ещё что за костыли? Надо отдельно сравнить errors и отдельно message. Зачем всё в строку толкать?

2020-05-08 09:07 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +                .build();
А почему ты ClientVersionCreateRequestDTO и ClientVersionDTO создаёшь в отдельных методах, а этот объект иначе? Надо придерживаться единообразия

2020-05-08 09:07 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        var actual = versions.getData().get(0);
почему только первый элемент? А если метод вернёт три объекта? Надо проверить, что вернулось нужное количество (hasSize(1)) и массив содержит ожидаемый элемент (contains(expected))

2020-05-08 09:07 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        verify(repository).save(Mockito.any());
ты ведь точно знаешь, что туда передавать - объект ClientVersion с полями, заполненными данными из requestDto

2020-05-08 09:07 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +    @EnumSource(value = Locale.class, names = {"ALL", "RU"})
locale вообще нигде не участвует, зачем его передавать в параметрах?

2020-05-08 09:07 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        assertTrue(actual.contains(expected));
уже писал выше, что сравнение строк это какой-то трэш

2020-05-08 09:07 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        String actual = exception.getMessage() + exception.getErrors().toString();
ты смотрел, какое значение принимает exception.getErrors().toString()?

2020-05-08 09:07 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        assertTrue(actual.contains(expected));
assertThat(actual).isEqualTo(expected)

2020-05-08 09:07 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        var clientVersion = Optional.of(new ClientVersion());
лучше наоборот - здесь:  var clientVersion = new ClientVersion();
ниже: when(repository.findById(ID)).thenReturn(Optional.of(clientVersion));
 затем: verify(repository).delete(clientVersion);

2020-05-08 09:07 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +    void whenDeleteShouldTrue() {
whenDeleteShouldTrue - шта?

2020-05-08 14:43 UTC, MuradTcen commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +    @EnumSource(value = Locale.class, names = {"ALL", "RU"})
`
@ParameterizedTest
    @EnumSource(value = Locale.class, names = {"ALL", "RU"})
    void whenCreateAndSameVersionIsNotPresetItShouldReturnClientVersionDTO(Locale locale) {
        var requestDto = getCreateRequestDto();
        requestDto.setLocale(locale);
`

Если я правильно понятл, то через locale мы сетим изменяемый параметр

2020-05-08 14:48 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +    @EnumSource(value = Locale.class, names = {"ALL", "RU"})
да, верно. Но потом в expected ты уже не делаешь разграничений, всегда ожидаешь один и тот же объект

2020-05-09 08:46 UTC, Smartel1 requested changes

2020-05-09 08:46 UTC, Smartel1 commented on src/main/java/ru/smartel/strike/entity/ClientVersion.java
> +    public boolean equals(Object o) {
переопределять equals в JPA сущностях - спорный вопрос. Я пока не вдавался в эту проблему, и не могу сказать, как лучше. Давай пока оставим как было, чтобы не было багов где-нибудь в другом месте программы

2020-05-09 08:46 UTC, Smartel1 commented on src/main/java/ru/smartel/strike/mapper/ClientVersionMapper.java
> +    ClientVersion ClientVersionCreateRequestDTOToClientVersion(ClientVersionCreateRequestDTO clientVersionCreateRequestDTO);
назови CreateRequestDTOToEntity. Так короче, и смысл не теряется

2020-05-09 08:46 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +    private static ClientVersionDTO getClientVersionDTO() {
этот метод статический, а getCreateRequestDto и clientVersionGetNewRequestDTO - нет. Ты уж определись)

2020-05-09 08:46 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +    // Check for throwing out ValidationException
лишний комментарий. Из названия метода и так понятно. В других методах тоже убери эти комменты

2020-05-09 08:46 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        String actualErrorMessage = exception.getErrors().get("error").get(0);
а что, если в exception попадут две ошибки вместо одной?

2020-05-09 08:46 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        var clientVersion = ClientVersionMapper.INSTANCE.ClientVersionCreateRequestDTOToClientVersion(requestDto);
проще было создать статический метод для ClientVersion. Использовать mapstruct в тестах, но не использовать в сервисе - это дурно пахнет. А что, если изменится логика маппинга в сервисе?

2020-05-09 08:46 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +    private static Stream<Arguments> provideLocaleForClientVersion() {
название метода вводит в заблуждение

2020-05-09 08:46 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        expectedForRuLocale.add("description", DESCRIPTION_RU);
создай уж тогда DESCRIPTION по аналогии с DESCRIPTION_RU, DESCRIPTION_EN...

2020-05-09 08:46 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +    void whenCreateAndSameVersionIsPresetItShouldThrowValidationException() {
опечатка в Present

2020-05-09 08:46 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +    void whenCreateAndSameVersionIsPresetItShouldThrowValidationException() {
название лучше написать так: create_whenSameVersionIsPresent_thenThrowValidationException

2020-05-09 08:46 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +    void whenCreateAndSameVersionIsPresetItShouldThrowValidationException() {
это будет соответствовать given-when-then

2020-05-09 08:47 UTC, Smartel1 commented on src/main/java/ru/smartel/strike/entity/ClientVersion.java
> +    public boolean equals(Object o) {
https://stackoverflow.com/questions/5031614/the-jpa-hashcode-equals-dilemma

2020-05-09 16:43 UTC, MuradTcen commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        var clientVersion = ClientVersionMapper.INSTANCE.ClientVersionCreateRequestDTOToClientVersion(requestDto);
Да, я думал о том, что в сервисе остался "ручной" маппинг. В голове у меня было такая последовательность, если ты заапрувишь применение mapstruct, то потом отрефакторить и в сервисе этот маппинг

Выпиливаю mapstruct

2020-05-10 14:19 UTC, Smartel1 requested changes

2020-05-10 14:19 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        expected.add(DESCRIPTION, null);
а это зачем тут?

2020-05-10 14:19 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        getNewRequestDto.setCurrentVersion("CURRENT_" + VERSION);
сделай VERSION равным "1.0.0" и убери "CURRENT_"

2020-05-10 14:19 UTC, Smartel1 commented on src/test/java/ru/smartel/strike/service/client_version/ClientVersionServiceTest.java
> +        getNewRequestDto.setCurrentVersion("CURRENT_" + VERSION);
если есть необходимость, можно сделать ещё одну константу, например VERSION_2 = "2.0.0"

2020-05-10 18:19 UTC, Smartel1 approved these changes

2020-05-10 18:44 UTC, merged